#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
#shellcheck disable 2154
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i.bak '49a\                add_header X-Served-By "\$hostname";' /etc/nginx/sites-available/default
sudo service nginx restart
